version: "3.7"
services:
  nifi:
    build: nifi/.
    container_name: nifi
    restart: on-failure
    ports:
      - "9090:9090"
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    networks:
      - nifi
    volumes:
      - nifidata:/opt/nifi/nifi-current/logs

volumes:
  nifidata:
    driver: local

networks:
  nifi: